ALTER SESSION SET CONTAINER = XEPDB1;

CREATE USER COROUTINES_CRUD IDENTIFIED BY 123456 ACCOUNT UNLOCK;

GRANT
    CREATE SESSION,
    CREATE TABLE,
    CREATE SEQUENCE,
    CREATE VIEW,
    CREATE SYNONYM,
    CREATE PUBLIC SYNONYM,
    DROP PUBLIC SYNONYM TO COROUTINES_CRUD;

ALTER SESSION SET CURRENT_SCHEMA = COROUTINES_CRUD;
ALTER USER COROUTINES_CRUD quota unlimited on USERS;